protected/models/Post.php
<?php
class Post extends CActiveRecord
{
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'posts';
    }

    public function relations()
    {
        return array(
            'PostCategory' => array(self::BELONGS_TO, 'PostCategory', 'post_cat_id'),
            'Vendor' => array(self::BELONGS_TO, 'Vendor', 'author_vid'),
            'User' => array(self::BELONGS_TO, 'User', 'author_uid')
        );
    }

    public function rules()
    {
        return array(
            array('title, content_1, content_2, tags', 'filter', 'filter' => 'trim'),
            array('title, tags', 'filter', 'filter' => 'htmlspecialchars'),

            array('content_1, content_2', 'filter', 'filter' => array('Post', 'postStripTags')),

            array('title, content_2', 'required',
                'message' => '&uarr; заполните это поле'),

            array('content_1', 'required', 'on' => 'verification',
                'message' => '&uarr; заполните это поле'),

            array('post_cat_id', 'required',
                'message' => '&uarr; выберите раздел'),

            array('title', 'length', 'min' => 5, 'max' => 200,
            'tooShort' => '&uarr; слишком короткое название',
            'tooLong' => '&uarr; слишком длинное название (максимум {max} символов)'),

            array('tags', 'safe'),
            array('status', 'unsafe'),
            array('status', 'in', 'range' => array('published', 'published_verification', 'verification', 'rejected', 'draft'))
        );
    }

    public static function postStripTags($value)
    {
        $value = strip_tags($value, '<h1><h2><h3><h4><h5><h6><a><p><strong><b><strike><ol><ul><li><img><iframe><table><tbody><th><tr><td><hr>');

        $value = preg_replace('/font\-family\:([\d\w\s,\'-]*)\;/i', '', $value);
        $value = preg_replace('/font\:([\d\w\s,\'-]*)\;/i', '', $value);

        return $value;
    }
}

protected/controllers/PostController.php
<?php
class PostController extends AppController
{

    public $pageTitle='';//Все для свадьбы и свадебных церемоний на портале svitor.ru
    public $pageDescription='На свадебном портале Вы найдете все для свадьбы. Мы поможем Вам ';
    public $pageKeywords='свадьба, торжество, мероприятие, портал, ';

    public function filters()
    {
        return array('accessControl');
    }

    public function accessRules()
    {
        return array(
            array('deny',
                'actions' => array('Add', 'Edit', 'Delete'),
                'users' => array('?')
            ),
            array('allow',
                'actions' => array('Add', 'Edit', 'Delete'),
                'users' => array('@')
            )
        );
    }

    public function actionIndex($cat = null)
    {
        $cat = strtolower(htmlspecialchars(trim($cat)));
        $active_category = array();
        $view_post = array();
        $recommendations = array();

        Yii::app()->name = 'Обмен опытом';

        if (!empty($cat))
            $active_category = PostCategory::model()->findByAttributes(array('name' => $cat));

        $criteria = new CDbCriteria;
        $criteria->condition = '(t.status = "published" OR t.status = "published_verification")';

        // Если есть активная категория
        if (!empty($active_category))
        {
            Yii::app()->name = $active_category->title;
            $criteria->condition .= ' AND t.post_cat_id = ' . $active_category->id;
        }

        $criteria->order = 'published_date DESC';
        $criteria->with = array('PostCategory');

        // Если есть что-то в поиске
        if (!empty($_GET['q']))
        {
            $query = htmlspecialchars(trim($_GET['q']));
            $query = str_replace('%', '\%', $query);
            $query = str_replace('_', '\_', $query);
            $criteria->condition .= ' AND (t.title LIKE "%'.$query.'%" OR t.content_1 LIKE "%'.$query.'%" OR t.content_2 LIKE "%'.$query.'%")';

            // Пишем в лог только если запрос был от гостя или обычного пользователя
            // запросы администраторов и модераторов не учитываются
            if (User::isGuest() || (!User::isGuest() && User::getSecurityLevel() == 0))
            {
                $log = new LogInfoSearch();
                $log['ip_address'] = ip2long(CHttpRequest::getUserHostAddress());
                $log['date'] = time();
                $log['query_text'] = $query;

                if (!User::isGuest())
                    $log['uid'] = User::getId();

                $log->save();
            }
        }

        $dataProvider = new CActiveDataProvider('Post', array(
            'pagination' => array(
                'pageSize' => Yii::app()->params['items_per_page'],
                'pageVar' => 'page'
            ),
            'criteria' => $criteria
        ));

        // Выбираем категории в которых есть хотябы один опубликованный пост
        $categories = PostCategory::model()->with(array(
            'Post' => array(
                'select' => false
            )))->findAll();

        $this->render('index', array(
            'active_category' => $active_category,
            'categories' => $categories,
            'posts' => $dataProvider->getData(),
            'posts_pagination' => $dataProvider->pagination,

            'view_post' => $view_post,
            'recommendations' => $recommendations
        ));
    }

    public function actionView($id = 0)
    {
        $id = intval($id);
        if (empty($id))
            $this->redirect(Yii::app()->createUrl('post'));

        $criteria = new CDbCriteria;
        $criteria->condition = '(t.status = "published" OR t.status = "published_verification") AND t.id = :post_id';
        $criteria->params = array(':post_id' => $id);
        $criteria->with = array('Vendor', 'User', 'PostCategory');

        $post = Post::model()->find($criteria);
        if (empty($post))
            $this->redirect(Yii::app()->createUrl('post'));

        Yii::app()->name = $post->title;

        // Фото
        $criteria = new CDbCriteria;
        $criteria->condition = 'post_id = :post_id';
        $criteria->params = array(':post_id' => $id);

        $postImages = PostImages::model()->findAll($criteria);

        // Читайте также
        $criteria = new CDbCriteria;
        $criteria->condition = '(t.status = "published" OR t.status = "published_verification") AND t.post_cat_id = :post_cat_id AND t.id != :post_id';
        $criteria->params = array(
            ':post_cat_id' => $post->post_cat_id,
            ':post_id' => $post->id
        );
        $criteria->order = 'published_date DESC';
        $criteria->limit = 5;

        $recommendations = Post::model()->findAll($criteria);

        // Комментарии
        $criteria = new CDbCriteria;
        $criteria->condition = '(t.status = "published") AND post_id = :post_id';
        $criteria->params = array(':post_id' => $post->id);
        $criteria->order = 'date ASC';
        $criteria->with = array('User');

        $dataProvider = new CActiveDataProvider('PostComment', array(
            'pagination' => array(
                'pageSize' => Yii::app()->params['items_per_page'],
                'pageVar' => 'page',
                'params' => array_merge($_GET, array('#' => 'comments'))
            ),
            'criteria' => $criteria
        ));

        $this->render('view', array(
            'postImages' => $postImages,
            'post' => $post,
            'recommendations' => $recommendations,
            'comments_count' => $dataProvider->getTotalItemCount(),
            'comments' => $dataProvider->getData(),
            'comments_pagination' => $dataProvider->pagination
        ));
    }

    public function actionAdd()
    {
        $model = new Post('add');

        if (isset($_POST['Post']))
        {
            $model->attributes = $_POST['Post'];
            $model['created_date'] = time();
            $model['status'] = 'verification';
            $model['author_uid'] = User::getId();

            if ($model->save(false))
                Yii::app()->user->setFlash('add_post_success', 'Спасибо! Ваш пост будет опубликован сразу после проверки - это займет некоторое время ;)');

            // Читайте также
            $criteria = new CDbCriteria;
            $criteria->order = 'id DESC';
            $criteria->limit = 1;

            $lastPost = Post::model()->find($criteria);
            $id = $lastPost->id;

            foreach(json_decode($_POST['images']) as $item){

                $post=new PostImages();
                $post->post_id=(int)$id;
                $post->image_big = $item->image_big;
                $post->image_medium = $item->image_medium;
                $post->save();
            }
        }

        $this->render('_form', array(
            'max_images' => 50,
            'model' => $model,
            'categories' => CHtml::listData(PostCategory::model()->findAll(), 'id', 'title')
        ));
    }

    public function actionAddComment()
    {
        if (User::isGuest())
            Yii::app()->end();

        $this->layout = 'ajax';

        $model = new PostComment('add');
        if (isset($_POST['Comment']))
        {
            // Проверим существует ли статья
            $post_id = intval($_POST['Comment']['post_id']);
            if (!$post = Post::model()->findByPk($post_id))
                Yii::app()->end();

            $model->attributes = $_POST['Comment'];
            $model['post_id'] = $post->id;
            $model['uid'] = User::getId();
            $model['date'] = time();

            if ($model->save()) {
                echo '{"status":"ok"}';
            } else {
                echo '{"status":"error", "msg":"'.str_replace('"', '\"', CHtml::error($model, 'comment')).'"}';
            }
        }
    }

    public function actionDeletephoto()
    {

        if (isset($_POST['path']) && isset($_POST['image']))
        {
            if(file_exists(DOCUMENT_ROOT."/".$_POST['path']."/".$_POST['image'])){
                unlink(DOCUMENT_ROOT."/".$_POST['path']."/".$_POST['image']);
            }
            if(file_exists(DOCUMENT_ROOT."/".$_POST['path']."/medium/".$_POST['image'])){
                unlink(DOCUMENT_ROOT."/".$_POST['path']."/medium/".$_POST['image']);
            }
        }
    }

    public function actionDeleteonephoto()
    {

        $criteria = new CDbCriteria;
        $criteria->condition = 'image_big = :image_big';
        $criteria->params = array(':image_big' => "/uploads_img/16796/".$_POST['image']);

        PostImages::model()->deleteAll($criteria);

        if (isset($_POST['path']) && isset($_POST['image']))
        {
            if(file_exists(DOCUMENT_ROOT."/".$_POST['path']."/".$_POST['image'])){
                unlink(DOCUMENT_ROOT."/".$_POST['path']."/".$_POST['image']);
            }
            if(file_exists(DOCUMENT_ROOT."/".$_POST['path']."/medium/".$_POST['image'])){
                unlink(DOCUMENT_ROOT."/".$_POST['path']."/medium/".$_POST['image']);
            }
        }
    }

    public function actionRemoveComment($id = 0)
    {
        $id = intval($id);
        if (empty($id))
            Yii::app()->end();

        if (User::isGuest())
            Yii::app()->end();

        $criteria = new CDbCriteria;
        $criteria->condition = 'uid = :uid AND id = :id';
        $criteria->params = array(':uid' => User::getId(), ':id' => $id);

        if (PostComment::model()->updateAll(array('deleted' => 1), $criteria))
            echo 'ok';
    }
}

protected/views/post/_comments.php
<?php if (!empty($comments)): ?>
    <?php foreach ($comments as $comment): ?>
    <?php $profile_url = Yii::app()->createUrl('user/profile', array('id' => $comment['User']['id'])); ?>

    <table id="comment_<?php echo $comment['id']; ?>" class="comment_table<?php if ($comment->deleted == 1) echo ' magic_button'; ?>">
    <tr>
        <td valign="top" width="55px">
            <a href="<?php echo $profile_url; ?>"><img src="<?php echo Yii::app()->ImgManager->getUrlById($comment['User']['img_id'], 'small', $comment['User']['img_filename']); ?>"></a>
        </td>
        <td valign="top" style="padding: 0 5px 5px;">
            <a href="<?php echo $profile_url; ?>" class="username"><?php echo $comment['User']['login']; ?></a>

            <?php if ($comment->deleted == 0): ?>
                <div class="comment_text"><?php echo nl2br($comment['comment']); ?></div>
                <div class="comment_info"><?php echo mApi::humanDatePrecise($comment['date']); ?>

                    <?php if ($comment['User']['id'] == User::getId()): ?>
                     | <a onclick="info.removeComment(<?php echo $comment['id']; ?>); return false;">удалить</a>
                    <?php endif; ?>
                </div>
            <?php else: ?>
                <div class="comment_deleted">Пользователь удалил свой комментарий...</div>
            <?php endif; ?>
        </td>
    </tr>
    </table>
    <?php endforeach; ?>
<?php else: ?>
    <div style="margin-top: 15px;">Пока нет ни одного комментария...</div>
<?php endif; ?>

<br>

<?php
$this->widget('CLinkPager', array(
    'pages' => $comments_pagination,
    'htmlOptions' => array('class' => 'b-default_pager'),
    'firstPageLabel' => '',
    'lastPageLabel' => '',
    'prevPageLabel' => '&larr; Назад',
    'nextPageLabel' => 'Далее &rarr;',
    'header' => ''
));
?>
<div id="trash-comment-dialog" title="Удалить комментарий" style="display: none;">Вы действительно хотите удалить свой комментарий?</div>

<div style="margin-top: 10px;" id="user_comment">
    <?php if (User::isGuest()): ?>

        Только <a href="<?php echo Yii::app()->createUrl('user/registration'); ?>">зарегистрированные</a> пользователи могут
        оставлять комментарии. <a href="<?php echo Yii::app()->createUrl('user/login'); ?>">Войти</a>.

    <?php else: ?>

        <b>Ваш комментарий:</b>
        <div id="comment_error"></div>

        <textarea style="width: 100%; height: 50px; margin: 10px 0;" id="comment"></textarea>

        <div class="button_main">
            <button onclick="info.sendComment(this, <?php echo $post_id; ?>);">Добавить</button>
        </div>
        <span style="color: #939393;"> (комментарий будет проверен модератором)</span>

    <?php endif; ?>
</div>

protected/views/post/_form.php
<h2>Новый пост</h2>
<br>
<?php if (Yii::app()->user->hasFlash('add_post_success')): ?>
<div class="msg_success"><?php echo Yii::app()->user->getFlash('add_post_success'); ?></div>
<?php else: ?>
<div class="simple_desc">
    Постарайтесь написать полезную для других информацию, отразив с какими проблемами вы столкнулись при организации или проведении праздника, от чего бы вы хотели уберечь читателя. Возможно, вы просто захотите рассказать об "изюминке" вашего праздника? Это тоже может быть кому-то полезно!<br><br>
</div>
<div class="simple_form">
    <?php echo CHtml::beginForm(); ?>

    <div class="item">
        <div class="label">Раздел:</div>
        <div class="field">
            <?php echo CHtml::activeDropDownList($model, 'post_cat_id', $categories, array('empty' => '-- не выбрано --')); ?>
            <?php echo CHtml::error($model, 'post_cat_id'); ?>
        </div>
    </div>

    <div class="item">
        <div class="label">Название:</div>
        <div class="field d_width_50">
            <?php echo CHtml::activeTextField($model, 'title'); ?>
            <?php echo CHtml::error($model, 'title'); ?>
        </div>
    </div>

    <div class="item">
        <div class="field">
            <div class="button_main"><button id="upload_image">Загрузить фотографии &rarr;</button></div>
        </div>
    </div>

    <div class="item">
        <div class="field d_width_100">
            <?php echo CHtml::activeTextArea($model, 'content_2'); ?>
            <?php echo CHtml::error($model, 'content_2'); ?>
        </div>
    </div>

    <div class="item">
        <div class="field">
            <div class="button_main"><button id="upload_images">Загрузить фотографии &rarr;</button></div>
        </div>
    </div>

    <div class="item">
        <div class="b-media-thumbs_title">Изображения <span id="images_counter"><span>0</span> / <?php echo $max_images; ?></span></div>
        <div class="b-media-thumbs" id="images_thumbs"></div>
        <span id="loader"></span>
        <input id="imagePost" type="hidden" name="images" value="">
    </div>

    <div class="item">
        <div class="field">
            <div class="button_main">
                <button><?php echo $model->isNewRecord ? 'Опубликовать' : 'Сохранить изменения'; ?></button>
            </div>
        </div>
    </div>

    <?php echo CHtml::endForm(); ?>
</div>

<script type="text/javascript" src="/static/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/static/ckeditor/adapters/jquery.js"></script>
<script src="/static/js/m_post_add.js"></script>
<script src="/static/js/ajaxupload.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#Post_content_2').ckeditor();
        post_add.uploadImg($('#upload_image'));
        post_add.uploadImg($('#upload_images'));
    });
</script>
<?php endif; ?>

protected/views/post/_posts_list.php
<?php foreach ($posts as $post): ?>
<?php $url = Yii::app()->createUrl('post/view', array('id' => $post->id)); ?>

<div class="post_wrap">
    <div class="post">
        <div class="title">
            <a href="<?php echo $url; ?>"><?php echo $post->title; ?></a>
        </div>
        <div class="body">
            <?php echo $post->content_1; ?>
            <div><a href="<?php echo $url; ?>">Читать дальше &rarr;</a></div>
        </div>
        <div class="post_infopanel">
            <ul class="info">
                <li>
                    <?php if (!empty($post['User'])): ?>
                    <?php $url = Yii::app()->createUrl('user/profile', array('id' => $post['User']['id'])); ?>
                    <b>Автор:</b> <a href="<?php echo $url; ?>"><?php echo $post['User']['login']; ?></a>

                    <?php elseif (!empty($post['Vendor'])): ?>
                    <?php $url = Yii::app()->createUrl('vendor/profile', array('id' => $post['Vendor']['id'])); ?>

                    <b>Автор:</b> &laquo;<a href="<?php echo $url; ?>"><?php echo mApi::cutStr($post['Vendor']['title'], 30); ?></a>&raquo;

                    <?php else: ?>
                    <b>Источник:</b> <a href="http://<?php echo Yii::app()->request->getServerName(); ?>"><?php echo Yii::app()->request->getServerName(); ?></a>
                    <?php endif; ?>
                </li>
                <li class="date">
                    <?php echo mApi::humanDatePrecise($post->published_date); ?>
                </li>
                <?php if (User::getSecurityLevel() > 0): ?>
                <?php Yii::app()->user->setReturnUrl(Yii::app()->request->url); ?>
                <li>
                    <a href="/mod_cp/post/edit/id/<?php echo $post->id; ?>">ред.</a>
                </li>
                <?php endif; ?>
            </ul>
            <div class="share42init sm_share r_fl"></div>
        </div>

    </div>
</div>

<?php endforeach; ?>
<?php
$this->widget('CLinkPager', array(
    'pages' => $posts_pagination,
    'htmlOptions' => array('class' => 'b-default_pager'),
    'firstPageLabel' => '',
    'lastPageLabel' => '',
    'prevPageLabel' => '&larr; Назад',
    'nextPageLabel' => 'Далее &rarr;',
    'header' => '',
    'cssFile' => false
));
?>

protected/views/post/index.php
<table class="b-catalog-table">
    <td class="menu catalog_categories">
        <div class="button_main">
            <button onclick="location.assign('<?php echo Yii::app()->createUrl('post/add'); ?>');">+ Написать пост</button>
        </div>

        <?php if (!empty($categories)): ?>
        <?php foreach ($categories as $cat): ?>
            <div class="root<?php if (!empty($active_category) && $active_category->id == $cat->id) echo ' active'; ?>">
                <a href="<?php echo Yii::app()->createUrl('post/index', array('cat' => $cat->name)); ?>"><?php echo $cat->title; ?></a>
            </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </td>

    <td class="content">
        <div class="posts_search">
            <?php echo CHtml::beginForm(Yii::app()->createUrl('post/index'), 'GET'); ?>
                <?php echo CHtml::textField('q', Yii::app()->request->getParam('q'), array('placeholder' => 'Поиск')); ?>
                <div class="button_grey">
                    <button type="submit">Найти</button>
                </div>
            <?php echo CHtml::endForm(); ?>
        </div>

        <?php
        if (!empty($posts)) {
            $this->renderPartial('_posts_list', array('posts' => $posts, 'posts_pagination' => $posts_pagination));
        } else {
            echo 'К сожалению нам не удалось ничего найти... :(';
        }
        ?>
    </td>
    <!-- <td class="params">

    </td> -->
</table>

protected/views/post/view.php
<?php
if($post->id == 50){
    $this->pageTitle='Русская свадьба и ее традиции';
    $this->pageDescription='На нашем портале Вы найдете все о традициях русской свадьбы.';
    $this->pageKeywords='русская, свадьба, традиции, портал, svitor.';
}elseif($post->id == 52){
    $this->pageTitle='Организация и проведение корпоративных мероприятий';
    $this->pageDescription='Мы подскажем Вам, с чего начать и как организовать корпоратив.';
    $this->pageKeywords='организация, корпоратив, портал, svitor.';
}
?>
<div class="post_wrap" style="width: 880px; margin: 0 auto;">
    <a href="<?php echo Yii::app()->createUrl('post/index'); ?>">Обмен опытом</a> / <a href="<?php echo Yii::app()->createUrl('post/index', array('cat' => $post['PostCategory']['name'])); ?>"><?php echo $post['PostCategory']['title']; ?></a>

    <h1 class="title"><?php echo $post->title; ?></h1>

    <div class="b-media-thumbs" id="images_thumbs">
        <?php foreach($postImages as $image):?>
        <div class="img" id="img_<?php echo $image["id"];?>">
            <a class="upbox-button" rel="upbox-button" href="<?php echo $image["image_big"];?>"><img src="<?php echo $image["image_medium"];?>"></a>
        </div>
        <?php endforeach; ?>
    </div>
    <div class="post_fulltext">
        <?php echo $post->content_1 . $post->content_2; ?>
    </div>

    <div class="post_infopanel">
        <ul class="info">
            <li>
                <?php if (!empty($post['User'])): ?>
                <?php $url = Yii::app()->createUrl('user/profile', array('id' => $post['User']['id'])); ?>
                <b>Автор:</b> <a href="<?php echo $url; ?>"><?php echo $post['User']['login']; ?></a>

                <?php elseif (!empty($post['Vendor'])): ?>
                <?php $url = Yii::app()->createUrl('vendor/profile', array('id' => $post['Vendor']['id'])); ?>

                <b>Автор:</b> &laquo;<a href="<?php echo $url; ?>"><?php echo mApi::cutStr($post['Vendor']['title'], 30); ?></a>&raquo;

                <?php else: ?>
                <b>Источник:</b> <a href="http://<?php echo Yii::app()->request->getServerName(); ?>"><?php echo Yii::app()->request->getServerName(); ?></a>
                <?php endif; ?>
            </li>
            <li class="date">
                <?php echo mApi::humanDatePrecise($post->published_date); ?>
            </li>
            <?php if (User::getSecurityLevel() > 0): ?>
            <?php Yii::app()->user->setReturnUrl(Yii::app()->request->url); ?>
            <li>
                <a href="/mod_cp/post/edit/id/<?php echo $post->id; ?>">ред.</a>
            </li>
            <?php endif; ?>
        </ul>
        <div class="share42init sm_share r_fl"></div>
    </div>

    <?php if (!empty($recommendations)): ?>
    <div class="recommendations_wrap">
        <h3>Читайте также</h3>
        <ul>
            <?php foreach ($recommendations as $recommend_post): ?>
            <?php $url = Yii::app()->createUrl('post/view', array('id' => $recommend_post['id'])); ?>
            <li>
                <a href="<?php echo $url; ?>"><?php echo mApi::cutStr($recommend_post['title'], 120); ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    <div class="comments_wrap">
        <h3 id="comments">Комментарии<?php echo !empty($comments_count) ? ' (' . $comments_count . ')' : ''; ?></h3>

        <?php
        $this->renderPartial('_comments', array(
            'comments_pagination' => $comments_pagination,
            'comments' => $comments,
            'post_id' => $post->id
        ))
        ?>
    </div>
</div>

<script src="/static/js/share42.js?<?php echo Yii::app()->params['version']['js']; ?>"></script>
<script src="/static/js/m_posts.js?<?php echo Yii::app()->params['version']['js']; ?>"></script>

<link rel="stylesheet" type="text/css" href="/static/fancybox/helpers/jquery.fancybox-buttons.css?<?php echo Yii::app()->params['version']['css']; ?>">
<script type="text/javascript" src="/static/fancybox/helpers/jquery.fancybox-buttons.js?<?php echo Yii::app()->params['version']['js']; ?>"></script>